### ISSUE TITLE
EventEmitter max listener warning.

### ISSUE THREAD

**Issue by abhishek-butola** [rtravitz/examples#1]
I am new to this event emitter. So for every new request there is new listener added right? And the default  listener value is 10 thats  why i am getting max listener warning ?

**Comment by rtravitz** [comment]
Hey @abhishek-butola that reads correct to me. It's a warning in place to help identify potential memory leaks. You can set the limit higher, but it's worth knowing that this is just a toy example, and it may not be useful for a real workload.

**Comment by abhishek-butola** [comment]
@rtravitz  Figured. Created array object managing the SSE requests and removed Event emitter implementation. If document changes then I can scan the array and send changes directly to user associated to that document.

**Comment by rtravitz** [comment]
> @rtravitz Figured. Created array object managing the SSE requests and removed Event emitter implementation. If document changes then I can scan the array and send changes directly to user associated to that document.

Seems like a good option!

**Comment by rtravitz** [comment]
Oh @abhishek-butola I did end up [adding a note to the original post](https://ryantravitz.com/2018-11-29-server-sent-events/) mentioning that the `EventEmitter` is a bad idea. Thanks for mentioning something about it!
